### ISSUE TITLE
采集脚本 有版本要求么？后面参数 可以使用默认的吧？

### ISSUE THREAD

**Issue by geespot** [GuyCheung/falcon-ngx_metric#18]
python nginx_collect.py --service=`hostname` --format=falcon --falcon-addr=http://127.0.0.1:1988/v1/push
Traceback (most recent call last):
  File "nginx_collect.py", line 451, in collect
    append_datapoint(datapoints, Render.render(la))
  File "nginx_collect.py", line 71, in render
    c = renders[la[0]]
KeyError: '<html>'

这个报错是  采集参数拿到一个html作为 key ?

**Comment by ryianyang** [comment]
遇到同样的问题，有没有解决办法？

**Comment by lingyuguo** [comment]
是因为nginx配置文件出现的问题

**Comment by ghost** [comment]
NGINX lua模块没有安装和配置好，导致访问执行lua脚本某个页面输出为 404 Not found page之类错误，Python脚本解释是抛出以上异常。

lua模块配置见
https://github.com/shuge/man2/blob/gh-pages/_drafts/www-servers/nginx/nginxQuickGuide.md#lua-%E6%94%AF%E6%8C%81

配置好lua模块和脚本目录，执行以下测试通过后，跑Python脚本应该就正常了。

    curl http://127.0.0.1:9091/monitor/basic_status
