### ISSUE TITLE
脚本执行错误

### ISSUE THREAD

**Issue by fengallan0** [GuyCheung/falcon-ngx_metric#26]
我执行脚本以后就报下面的错，请问是什么导致的呢，谢谢！
[root@fqy-nginx-4 falcon-ngx_metric]# python nginx_collect.py --format=falcon
Traceback (most recent call last):
  File "nginx_collect.py", line 450, in collect
    append_datapoint(datapoints, Render.render(la))
  File "nginx_collect.py", line 70, in render
    c = renders[la[0]]
KeyError: '<html>'

**Comment by mykioer** [comment]
同问，不知道是不是因为log_by_lua_file这个没装

**Comment by mykioer** [comment]
/usr/local/openresty/nginx/conf.d/ngx_metric.conf配置文件中lua_package_path一行配置为绝对路径
`lua_package_path "/usr/local/openresty/nginx/modules/?.lua;;";`
