### ISSUE TITLE
执行脚本有报错

### ISSUE THREAD

**Issue by law-lee** [GuyCheung/falcon-ngx_metric#6]
Traceback (most recent call last):
  File "nginx_collect.py", line 450, in collect
    append_datapoint(datapoints, Render.render(la))
  File "nginx_collect.py", line 70, in render
    c = renders[la[0]]
KeyError: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">'

**Comment by law-lee** [comment]
是我自己nginx配置原因，执行脚本的机器没有访问权限。
